A second approach to detect videodev2.h for V4L2 support. Added a xioclt function like V4L2 API explain. Implemente vid_close for V4L2 as separate function to implement stop capturing as V4L2 explain.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4861,10 +4861,23 @@ else
 fi
 
 
+{ echo "$as_me:$LINENO: checking for V42L support" >&5
+echo $ECHO_N "checking for V42L support... $ECHO_C" >&6; }
+if test x$have_v4l2 = xtrue; then
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	TEMP_CFLAGS="${TEMP_CFLAGS} -DHAVE_V4L2"
+else
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
 if test x$have_v4l2 = xfalse; then
-	{ echo "$as_me:$LINENO: checking for struct v4l2_buffer" >&5
-echo $ECHO_N "checking for struct v4l2_buffer... $ECHO_C" >&6; }
-if test "${ac_cv_type_struct_v4l2_buffer+set}" = set; then
+	{ echo "$as_me:$LINENO: checking for V42L *old* support" >&5
+echo $ECHO_N "checking for V42L *old* support... $ECHO_C" >&6; }
+	{ echo "$as_me:$LINENO: checking for linux/videodev2.h" >&5
+echo $ECHO_N "checking for linux/videodev2.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_videodev2_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -4873,17 +4886,84 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <sys/time.h>
-                #include <linux/videodev2.h>
 
-typedef struct v4l2_buffer ac__type_new_;
+					#ifdef __linux__
+					#include <linux/types.h>
+					#endif
+
+
+#include <linux/videodev2.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_linux_videodev2_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_header_linux_videodev2_h=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_videodev2_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_videodev2_h" >&6; }
+if test $ac_cv_header_linux_videodev2_h = yes; then
+  have_v4l2_old=true
+else
+
+		    			{ echo "$as_me:$LINENO: checking for linux/videodev2.h with sys/types.h" >&5
+echo $ECHO_N "checking for linux/videodev2.h with sys/types.h... $ECHO_C" >&6; }
+					cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+					#ifdef __linux__
+					#include <sys/types.h>
+					#include <linux/types.h>
+					#endif
+
 int
 main ()
 {
-if ((ac__type_new_ *) 0)
-  return 0;
-if (sizeof (ac__type_new_))
-  return 0;
+
+				        	return 0;
+
   ;
   return 0;
 }
@@ -4922,32 +5002,33 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_type_struct_v4l2_buffer=yes
+
+				       	have_v4l2_old=true
+				        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_type_struct_v4l2_buffer=no
+
+				        { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_type_struct_v4l2_buffer" >&5
-echo "${ECHO_T}$ac_cv_type_struct_v4l2_buffer" >&6; }
-if test $ac_cv_type_struct_v4l2_buffer = yes; then
-  have_v4l2=true have_v4l2_old=true
-else
-  have_v4l2=false
-fi
 
 fi
 
-if test x$have_v4l2 = xtrue; then
-	TEMP_CFLAGS="${TEMP_CFLAGS} -DHAVE_V4L2"
-	if test x$have_v4l2_old = xtrue; then
-		TEMP_CFLAGS="${TEMP_CFLAGS} -DHAVE_V4L2_OLD"
-	fi
+
 fi
+
+if test x$have_v4l2_old = xtrue; then
+	TEMP_CFLAGS="${TEMP_CFLAGS} -DHAVE_V4L2 -DHAVE_V4L2_OLD"
+	have_v4l2=true
+fi
+
 
 
 { echo "$as_me:$LINENO: checking for short int" >&5
